# Generated by Django 3.0.3 on 2020-03-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='name',
            field=models.CharField(max_length=200, verbose_name='图片说明'),
        ),
    ]
