# Generated by Django 2.2.10 on 2020-04-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_db', '0003_auto_20200324_2233'),
        ('img_db', '0003_auto_20200326_2028'),
    ]

    operations = [
    ]
