# Generated by Django 3.0.3 on 2020-03-04 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0006_auto_20200302_2000'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': '施工日报'},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='plan',
        ),
        migrations.AddField(
            model_name='topic',
            name='days',
            field=models.IntegerField(default=0, verbose_name='工期（天）'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='cement',
            field=models.FloatField(default=0, verbose_name='水泥量'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='施工日期'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='footage',
            field=models.FloatField(default=0, verbose_name='进尺'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='rock',
            field=models.FloatField(default=0, verbose_name='出矸量'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=models.TextField(verbose_name='施工日报'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.Topic', verbose_name='工程名称'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='water',
            field=models.FloatField(default=0, verbose_name='排水量'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='worker',
            field=models.IntegerField(default=0, verbose_name='出勤人数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='character',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='技术特征'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='topic',
            name='end_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='完工时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='工程量'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='开工时间'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='工程名称'),
        ),
    ]
