# Generated by Django 3.0.3 on 2020-03-05 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('note', '0007_auto_20200304_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位名称'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='character',
            field=models.CharField(max_length=255, verbose_name='技术特征'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=200, verbose_name='工程名称'),
        ),
    ]
