# Generated by Django 3.0.3 on 2020-03-05 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('note', '0008_auto_20200305_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='单位名称'),
        ),
    ]
