# Generated by Django 3.0.3 on 2020-03-19 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0010_entry_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='施工单位'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='footage',
            field=models.FloatField(default=0, verbose_name='进  尺'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='worker',
            field=models.IntegerField(verbose_name='出勤人数'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='施工单位'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='days',
            field=models.IntegerField(default=0, verbose_name='工期(天)'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='工 程 量'),
        ),
    ]
