# Generated by Django 3.0.3 on 2020-03-20 04:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0011_auto_20200319_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='cement',
            field=models.FloatField(default=0, verbose_name='水泥/砼量'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='footage',
            field=models.FloatField(default=0, verbose_name='工程进度'),
        ),
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.AddField(
            model_name='entry',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='记录人'),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='owner',
        ),
        migrations.AddField(
            model_name='topic',
            name='owner',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='管理员'),
        ),
    ]
