# Generated by Django 3.0.4 on 2020-03-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_auto_20200320_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name': '施工日报', 'verbose_name_plural': '施工日报'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': '单位工程', 'verbose_name_plural': '单位工程'},
        ),
    ]
