# Generated by Django 2.2.10 on 2020-04-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_auto_20200324_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='owner',
            new_name='recorder',
        ),
        migrations.AlterField(
            model_name='entry',
            name='cement',
            field=models.FloatField(default=0, verbose_name='喷砼'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='footage',
            field=models.FloatField(default=0, verbose_name='进尺'),
        ),
    ]
