# Generated by Django 2.2.10 on 2020-04-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_auto_20200326_2028'),
        ('note', '0015_auto_20200421_2318'),
    ]

    operations = [
    ]
